data:
    name: 'coco'
    resize: [480,640]

    image_train_path: ['./data/BIPEDv2/BIPED/edges/imgs/train/rgbr/real',]
    label_train_path: ['./data/BIPEDv2/BIPED/edges/imgs/train/rgbr/',]
    image_test_path: './data/coco/images_v2/test2017/'
    label_test_path: 
    data_dir: './data/mg_coco_coco_3e-2'

    augmentation:
        photometric:
            train_enable: true
            test_enable: true
            
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.3, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                    nb_ellipses: 20
                motion_blur: {max_kernel_size: 3}
        homographic:
            train_enable: true
            test_enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57
                allow_artifacts: true
            valid_border_margin: 3
model:
    name: 'superedge'
    using_bn: true
    grid_size: 8
    det_thresh: 0.015 # 1/65
    nms: 8
    topk: -1
    pretrained_model: './export/superedge/superedge_2.506_139.pth'  

    backbone:
        backbone_type: 'VGG'
        vgg:
            channels: [64,64,64,64,128,128,128,128]
    det_head: #detector head
        feat_in_dim: 128
solver:
    grid_size: 8
    epoch: 100
    base_lr: 0.001
    train_batch_size: 1
    test_batch_size: 1
    save_dir: './export/pl/coco_v1'
    model_name: 'pl_cocov1'


